### ISSUE TITLE
Multiply sensors over I2C bus

### ISSUE THREAD

**Issue by milan-de** [ControlEverythingCommunity/BME280#3]
Hi together,

is there any possibility to have 2 or more sensor in parallel connected over I2C bus, so to be able to masure on two different points temperature at the same time ? If yes, how to set different address to different sensors ? It seems that all are having address 0x76 per default.

regards,
Milan

**Comment by ryker1990** [comment]
You can connect jumper pins on one of the sensors and it will show a different address.

**Comment by milan-de** [comment]
Sound easy but am I going to get conflicts over clock/data line as one sensor will be master and another slave ...arduino is always master ?

**Comment by milan-de** [comment]
Thanks ryker1990 i will do so !
